# Use an official Python runtime as a parent image
FROM python:3.13

# Set the working directory in the container
WORKDIR /app

# Copy scripts, config, and requirements.txt into the container
COPY ../scripts /app/scripts
COPY ../config/config.yaml /app/config/config.yaml
COPY ../docs/requirements.txt /app/requirements.txt

# Install necessary packages and Python dependencies
RUN apt-get update && \
    apt-get install -y bash mysql-client && \
    pip install --no-cache-dir -r /app/requirements.txt

# Expose port 8080 for the application
EXPOSE 8080

# Command to run when starting the container
CMD ["bash", "scripts/gui.sh"]