services:
  app:
    build:
      context: ..  
      dockerfile: docker/Dockerfile 
    privileged: true
    ports:
      - "5001:5001"  # Map host port 5001 to container port 5001
    volumes:
      - ../:/app  # Mount the entire project directory for easier access to scripts and configs
    environment:
      DATABASE_URL: "sqlite:///app/data/system_metrics.db"
      DISPLAY: "host.docker.internal:0" 

networks:
  OverClockedNetwork:
    driver: bridge
