database:
  name: "metrics_db"  # Name of the SQLite database file (without .db extension)

metrics:
  log_interval: 300  # Interval to log metrics in seconds
  output_format: "csv"  # Output format for metrics (options: csv or database)

gui:
  port: 5001  # Port on which the GUI will run
  theme: "dark"  # Theme for the GUI (light/dark)

logging:
  level: "INFO"  # Logging level (DEBUG, INFO, WARNING, ERROR)
  log_file: "/app/logs/app.log"  # Path to the log file

# Optional settings for metrics collection
metrics_collection:
  enabled: true  # Enable or disable metrics collection
